compressionLevel: mixed

enableGlobalCache: false

yarnPath: .yarn/releases/yarn-4.5.0.cjs

packageExtensions:
  "@nx/devkit@*":
    dependencies:
      "@angular-devkit/architect": "*"
  "@angular-eslint/eslint-plugin-template@*":
    dependencies:
      "@typescript-eslint/types": "*"
  "@angular-eslint/eslint-plugin@*":
    dependencies:
      "@typescript-eslint/utils": "*"
